### ISSUE TITLE
Some questions about HAPPO implementation

### ISSUE THREAD

**Issue by sachiel321** [cyanrain7/TRPO-in-MARL#10]
![45e703d34e3718481a732fbc49b7412](https://user-images.githubusercontent.com/48275474/176175837-4b00ffd3-5d8c-4078-9264-b7c22644d59b.png)
The above is the equation(10) in the paper, but I can't find it in the current implementation.

In the file <happo_trainer.py> 
![737eb5d5d035c88f44ec05ad85a9b1d](https://user-images.githubusercontent.com/48275474/176176454-17eaeb46-1bfd-4fd1-a419-d1df9e578694.png)

And <separated_buffer.py>
![baa6d02351ad0e8c4ebeecfcf7962eb](https://user-images.githubusercontent.com/48275474/176176594-d0f7e713-8f4a-4e3c-95b2-61d1ab42f81f.png)

I can not find any preprocessing to advantages like equation (10) in your paper.

I would appreciate knowing how iterative updates in the algorithm1 are represented in the code.

**Comment by sachiel321** [comment]
I figured it out... Your perpare each agent a trainer in <runner.py>.

**Comment by GoingMyWay** [comment]
@sachiel321 Hi, I cannot find the implementation either. Can you point out where I can find it?
