### ISSUE TITLE
Question about observation and state in multi-agent mujoco tasks

### ISSUE THREAD

**Issue by maxiao94** [cyanrain7/TRPO-in-MARL#11]
I have a question on multi-agent mujoco tasks.
For an agent, the global state and its observation seem to be the same in mujoco_multi.py.
Have I misunderstood the code？

**Comment by cyanrain7** [comment]
> I have a question on multi-agent mujoco tasks. For an agent, the global state and its observation seem to be the same in mujoco_multi.py. Have I misunderstood the code？

yes, in ma-mujoco, the setting of our experiment is MDP, not POMDP, the observation of each agent is global state and the one-hot vector of agent index. You also can modify the environment as POMDP, in mujoco_multi.py.
