### ISSUE TITLE
I found that the action value exceeds the limit

### ISSUE THREAD

**Issue by ollehhello** [cyanrain7/TRPO-in-MARL#3]
![image](https://user-images.githubusercontent.com/48572954/160539138-daac9344-f13a-4b37-8179-8156e227742c.png)

Hello, I found that the action value is not between [-1,+1].

**Comment by cyanrain7** [comment]
> ![image](https://user-images.githubusercontent.com/48572954/160539138-daac9344-f13a-4b37-8179-8156e227742c.png)
> 
> Hello, I found that the action value is not between [-1,+1].

wow!~  You find a error of the environment, thanks for pointing it! This error is not caused by our algorithm, so you can use some method to avoid it, and actually you did it, good job!
