### ISSUE TITLE
I found a bug in file 'utils/util.py'. If we use discrete action space in 'runners\separated\mujoco_runner.py' and store it's transition in buffer, we will get a bug. Because the act_shape is a constant value.

### ISSUE THREAD

**Issue by chillybird** [cyanrain7/TRPO-in-MARL#7]
![image](https://user-images.githubusercontent.com/42727973/168709301-ff9e09de-40c1-4c95-8163-3ecb2e0caa75.png)
I test it in MPE

**Comment by cyanrain7** [comment]
> ![image](https://user-images.githubusercontent.com/42727973/168709301-ff9e09de-40c1-4c95-8163-3ecb2e0caa75.png) I test it in MPE

About the MPE runner, maybe you can refer the share version in MAPPO repo, it have some difference with mujoco runner.

**Comment by chillybird** [comment]
I understand ，thank you.
