### ISSUE TITLE
conflicting dependicies and distribution of some packages not found

### ISSUE THREAD

**Issue by NessrineTrabelsi** [cyanrain7/TRPO-in-MARL#9]
Hi, 
I am trying to install the packages in the requirements file but I got errors, like matplotlib and tensorflow versions are not found and conflicting dependicies; Any clue how to fix this?
Thank you

**Comment by cyanrain7** [comment]
> Hi, I am trying to install the packages in the requirements file but I got errors, like matplotlib and tensorflow versions are not found and conflicting dependicies; Any clue how to fix this? Thank you

matplotlib and tensorboardX just used for plot experiment result, you can install a suitable version according to your environment~
